services:
  nginx:
    container_name: nebus_nginx
    image: nginx:1.27.4-alpine
    volumes:
      - ./src:/var/www
      - ./docker/nginx/config/$NGINX_CONFIG:/etc/nginx/conf.d/default.conf
      - ./.storage/logs/nginx:/var/log/nginx
    ports:
      - ${NGINX_PORT}:80
    depends_on:
      - app
    networks:
      - backend
    restart: always

  app:
    container_name: nebus_app
    build:
      context: docker/app
      args:
        - PHP_VERSION=$PHP_VERSION
        - UID=$UID
        - GID=$GID
    volumes:
      - ./src:/var/www
      - ./docker/app/config/php.ini:/usr/local/etc/php/php.ini
    user: ${UID}
    depends_on:
      - redis
    networks:
      - backend
    restart: always

  swagger:
    container_name: nebus_swagger
    image: swaggerapi/swagger-ui:v5.19.0
    ports:
      - ${SWAGGER_PORT}:8080
    environment:
      SWAGGER_JSON: "/oas/index.yaml"
      DOC_EXPANSION: "none"
    volumes:
      - ./src/public/oas:/oas
    depends_on:
      - nginx
    networks:
      - backend
    restart: always

  redis:
    container_name: nebus_redis
    image: redis:7.4.2
    command:
      - 'redis-server'
      - '--save 60 100'
      - '--loglevel warning'
    volumes:
      - ./.storage/redis:/data
    ports:
      - ${REDIS_PORT}:6379
    networks:
      - backend
    restart: always

networks:
  backend:
    driver: bridge
